version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: digging-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nginx.tmpl:/app/nginx.tmpl
    restart: always
    networks: 
      - proxy                                             

networks:
  proxy:
    driver: bridge